name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:
    name: Container de teste
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publicar no Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASS}}
          tags: latest, ${{ github.run_number}}
          image: tiagocerqueiro/teste1
          registry: docker.io
          dockerfile: Dockerfile
    
