name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:
    name: Container de teste
    runs-on: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publicar no Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: tiagocerqueiro/test1
          tags: latest
          registry: docker.io
          username: ${{ secrets.USER}}
          password: ${{ secrets.PASS}}
          repository: tiagocerqueiro/teste1
    
